In [2]:
import pandas as pd
import numpy as np

Read the information of players' regular totalstats

In [93]:
data_player_regular_totalstats = pd.read_csv('player_regular_totalstats.csv')
data_player_regular_totalstats.head(10)

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Unnamed: 0</th>
      <th>PLAYER_ID</th>
      <th>LEAGUE_ID</th>
      <th>TEAM_ID</th>
      <th>GP</th>
      <th>GS</th>
      <th>MIN</th>
      <th>FGM</th>
      <th>FGA</th>
      <th>FG_PCT</th>
      <th>...</th>
      <th>FT_PCT</th>
      <th>OREB</th>
      <th>DREB</th>
      <th>REB</th>
      <th>AST</th>
      <th>STL</th>
      <th>BLK</th>
      <th>TOV</th>
      <th>PF</th>
      <th>PTS</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>76001</td>
      <td>0</td>
      <td>0</td>
      <td>256</td>
      <td>53.0</td>
      <td>3200.0</td>
      <td>620</td>
      <td>1236</td>
      <td>0.501618</td>
      <td>...</td>
      <td>0.700934</td>
      <td>283.0</td>
      <td>563.0</td>
      <td>846.0</td>
      <td>85</td>
      <td>71.0</td>
      <td>69.0</td>
      <td>247.0</td>
      <td>484</td>
      <td>1465</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>76002</td>
      <td>0</td>
      <td>0</td>
      <td>505</td>
      <td>NaN</td>
      <td>11023.0</td>
      <td>1769</td>
      <td>4138</td>
      <td>0.427501</td>
      <td>...</td>
      <td>0.727857</td>
      <td>503.0</td>
      <td>1124.0</td>
      <td>4065.0</td>
      <td>601</td>
      <td>131.0</td>
      <td>205.0</td>
      <td>11.0</td>
      <td>1120</td>
      <td>4557</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
      <td>76003</td>
      <td>0</td>
      <td>0</td>
      <td>1560</td>
      <td>1476.0</td>
      <td>57446.0</td>
      <td>15837</td>
      <td>28307</td>
      <td>0.559472</td>
      <td>...</td>
      <td>0.721410</td>
      <td>2975.0</td>
      <td>9394.0</td>
      <td>17440.0</td>
      <td>5660</td>
      <td>1160.0</td>
      <td>3189.0</td>
      <td>2527.0</td>
      <td>4657</td>
      <td>38387</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
      <td>51</td>
      <td>0</td>
      <td>0</td>
      <td>586</td>
      <td>336.0</td>
      <td>15627.0</td>
      <td>3514</td>
      <td>7943</td>
      <td>0.442402</td>
      <td>...</td>
      <td>0.905254</td>
      <td>219.0</td>
      <td>868.0</td>
      <td>1087.0</td>
      <td>2079</td>
      <td>487.0</td>
      <td>46.0</td>
      <td>963.0</td>
      <td>1106</td>
      <td>8553</td>
    </tr>
    <tr>
      <th>4</th>
      <td>4</td>
      <td>1505</td>
      <td>0</td>
      <td>0</td>
      <td>236</td>
      <td>145.0</td>
      <td>4809.0</td>
      <td>720</td>
      <td>1726</td>
      <td>0.417149</td>
      <td>...</td>
      <td>0.703213</td>
      <td>286.0</td>
      <td>490.0</td>
      <td>776.0</td>
      <td>266</td>
      <td>184.0</td>
      <td>83.0</td>
      <td>309.0</td>
      <td>485</td>
      <td>1830</td>
    </tr>
    <tr>
      <th>5</th>
      <td>5</td>
      <td>949</td>
      <td>0</td>
      <td>0</td>
      <td>830</td>
      <td>704.0</td>
      <td>28882.0</td>
      <td>5434</td>
      <td>11515</td>
      <td>0.471906</td>
      <td>...</td>
      <td>0.810439</td>
      <td>1869.0</td>
      <td>4370.0</td>
      <td>6239.0</td>
      <td>2109</td>
      <td>820.0</td>
      <td>638.0</td>
      <td>2136.0</td>
      <td>2324</td>
      <td>15028</td>
    </tr>
    <tr>
      <th>6</th>
      <td>6</td>
      <td>76005</td>
      <td>0</td>
      <td>0</td>
      <td>319</td>
      <td>40.0</td>
      <td>5434.0</td>
      <td>724</td>
      <td>1472</td>
      <td>0.491847</td>
      <td>...</td>
      <td>0.747178</td>
      <td>374.0</td>
      <td>637.0</td>
      <td>1011.0</td>
      <td>384</td>
      <td>185.0</td>
      <td>60.0</td>
      <td>129.0</td>
      <td>525</td>
      <td>1779</td>
    </tr>
    <tr>
      <th>7</th>
      <td>7</td>
      <td>76006</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>NaN</td>
      <td>1.0</td>
      <td>0</td>
      <td>2</td>
      <td>0.000000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.0</td>
      <td>1</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>8</td>
      <td>76007</td>
      <td>0</td>
      <td>0</td>
      <td>56</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>203</td>
      <td>855</td>
      <td>0.237426</td>
      <td>...</td>
      <td>0.686486</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>37</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>171</td>
      <td>533</td>
    </tr>
    <tr>
      <th>9</th>
      <td>9</td>
      <td>203518</td>
      <td>0</td>
      <td>0</td>
      <td>172</td>
      <td>16.0</td>
      <td>2763.0</td>
      <td>304</td>
      <td>785</td>
      <td>0.387261</td>
      <td>...</td>
      <td>0.879629</td>
      <td>49.0</td>
      <td>198.0</td>
      <td>247.0</td>
      <td>88</td>
      <td>92.0</td>
      <td>22.0</td>
      <td>72.0</td>
      <td>289</td>
      <td>921</td>
    </tr>
  </tbody>
</table>
<p>10 rows Ã— 25 columns</p>
</div>

Check the missing of the data

In [94]:
data_player_regular_totalstats.apply(lambda x: sum(x.isnull()),axis=0)

Unnamed: 0       0
PLAYER_ID        0
LEAGUE_ID        0
TEAM_ID          0
GP               0
GS            1398
MIN            334
FGM              0
FGA              0
FG_PCT           0
FG3M          1285
FG3A          1285
FG3_PCT       1531
FTM              0
FTA              0
FT_PCT           0
OREB           981
DREB           981
REB            292
AST              0
STL            981
BLK            981
TOV           1183
PF               0
PTS              0
dtype: int64

Deal with the missing part of 'GS'

In [96]:
miss_GS = np.where(pd.isnull(data_player_regular_totalstats['GS']))
miss_GS

(array([   1,    7,    8, ..., 4323, 4332, 4334], dtype=int64),)

Change the missing part of 'GS' into 0

In [98]:
data_player_regular_totalstats.ix[miss_GS[0], 'GS'] = int(0)
data_player_regular_totalstats.ix[miss_GS[0],:]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Unnamed: 0</th>
      <th>PLAYER_ID</th>
      <th>LEAGUE_ID</th>
      <th>TEAM_ID</th>
      <th>GP</th>
      <th>GS</th>
      <th>MIN</th>
      <th>FGM</th>
      <th>FGA</th>
      <th>FG_PCT</th>
      <th>...</th>
      <th>FT_PCT</th>
      <th>OREB</th>
      <th>DREB</th>
      <th>REB</th>
      <th>AST</th>
      <th>STL</th>
      <th>BLK</th>
      <th>TOV</th>
      <th>PF</th>
      <th>PTS</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>76002</td>
      <td>0</td>
      <td>0</td>
      <td>505</td>
      <td>0.0</td>
      <td>11023.0</td>
      <td>1769</td>
      <td>4138</td>
      <td>0.427501</td>
      <td>...</td>
      <td>0.727857</td>
      <td>503.0</td>
      <td>1124.0</td>
      <td>4065.0</td>
      <td>601</td>
      <td>131.0</td>
      <td>205.0</td>
      <td>11.0</td>
      <td>1120</td>
      <td>4557</td>
    </tr>
    <tr>
      <th>7</th>
      <td>7</td>
      <td>76006</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0.0</td>
      <td>1.0</td>
      <td>0</td>
      <td>2</td>
      <td>0.000000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.0</td>
      <td>1</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1</td>
      <td>0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>8</td>
      <td>76007</td>
      <td>0</td>
      <td>0</td>
      <td>56</td>
      <td>0.0</td>
      <td>NaN</td>
      <td>203</td>
      <td>855</td>
      <td>0.237426</td>
      <td>...</td>
      <td>0.686486</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>37</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>171</td>
      <td>533</td>
    </tr>
    <tr>
      <th>11</th>
      <td>11</td>
      <td>76008</td>
      <td>0</td>
      <td>0</td>
      <td>28</td>
      <td>0.0</td>
      <td>220.0</td>
      <td>14</td>
      <td>63</td>
      <td>0.222222</td>
      <td>...</td>
      <td>0.535714</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>15.0</td>
      <td>23</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>43</td>
      <td>43</td>
    </tr>
    <tr>
      <th>13</th>
      <td>13</td>
      <td>76010</td>
      <td>0</td>
      <td>0</td>
      <td>23</td>
      <td>0.0</td>
      <td>195.0</td>
      <td>29</td>
      <td>74</td>
      <td>0.391891</td>
      <td>...</td>
      <td>0.655172</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>47.0</td>
      <td>11</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>35</td>
      <td>77</td>
    </tr>
    <tr>
      <th>16</th>
      <td>16</td>
      <td>76012</td>
      <td>0</td>
      <td>0</td>
      <td>487</td>
      <td>0.0</td>
      <td>12407.0</td>
      <td>1682</td>
      <td>4186</td>
      <td>0.401815</td>
      <td>...</td>
      <td>0.738983</td>
      <td>364.0</td>
      <td>844.0</td>
      <td>2732.0</td>
      <td>869</td>
      <td>283.0</td>
      <td>55.0</td>
      <td>NaN</td>
      <td>1591</td>
      <td>4236</td>
    </tr>
    <tr>
      <th>24</th>
      <td>24</td>
      <td>76015</td>
      <td>0</td>
      <td>0</td>
      <td>462</td>
      <td>0.0</td>
      <td>10427.0</td>
      <td>1381</td>
      <td>3330</td>
      <td>0.414714</td>
      <td>...</td>
      <td>0.712914</td>
      <td>41.0</td>
      <td>123.0</td>
      <td>1129.0</td>
      <td>1606</td>
      <td>106.0</td>
      <td>9.0</td>
      <td>NaN</td>
      <td>990</td>
      <td>3579</td>
    </tr>
    <tr>
      <th>32</th>
      <td>32</td>
      <td>76018</td>
      <td>0</td>
      <td>0</td>
      <td>86</td>
      <td>0.0</td>
      <td>712.0</td>
      <td>129</td>
      <td>367</td>
      <td>0.351498</td>
      <td>...</td>
      <td>0.676470</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>177.0</td>
      <td>39</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>130</td>
      <td>304</td>
    </tr>
    <tr>
      <th>37</th>
      <td>37</td>
      <td>76020</td>
      <td>0</td>
      <td>0</td>
      <td>78</td>
      <td>0.0</td>
      <td>844.0</td>
      <td>103</td>
      <td>352</td>
      <td>0.292613</td>
      <td>...</td>
      <td>0.597826</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>329.0</td>
      <td>24</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>170</td>
      <td>261</td>
    </tr>
    <tr>
      <th>49</th>
      <td>49</td>
      <td>76028</td>
      <td>0</td>
      <td>0</td>
      <td>27</td>
      <td>0.0</td>
      <td>232.0</td>
      <td>14</td>
      <td>43</td>
      <td>0.325581</td>
      <td>...</td>
      <td>0.555555</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>56.0</td>
      <td>10</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>27</td>
      <td>48</td>
    </tr>
    <tr>
      <th>55</th>
      <td>55</td>
      <td>76027</td>
      <td>0</td>
      <td>0</td>
      <td>702</td>
      <td>0.0</td>
      <td>20159.0</td>
      <td>3884</td>
      <td>8385</td>
      <td>0.463208</td>
      <td>...</td>
      <td>0.759851</td>
      <td>381.0</td>
      <td>928.0</td>
      <td>2205.0</td>
      <td>3174</td>
      <td>604.0</td>
      <td>124.0</td>
      <td>247.0</td>
      <td>1799</td>
      <td>9407</td>
    </tr>
    <tr>
      <th>60</th>
      <td>60</td>
      <td>76029</td>
      <td>0</td>
      <td>0</td>
      <td>36</td>
      <td>0.0</td>
      <td>166.0</td>
      <td>17</td>
      <td>78</td>
      <td>0.217948</td>
      <td>...</td>
      <td>0.540983</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>45.0</td>
      <td>10</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>34</td>
      <td>67</td>
    </tr>
    <tr>
      <th>71</th>
      <td>71</td>
      <td>76034</td>
      <td>0</td>
      <td>0</td>
      <td>33</td>
      <td>0.0</td>
      <td>373.0</td>
      <td>55</td>
      <td>143</td>
      <td>0.384615</td>
      <td>...</td>
      <td>0.547619</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>69.0</td>
      <td>29</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>32</td>
      <td>133</td>
    </tr>
    <tr>
      <th>76</th>
      <td>76</td>
      <td>76035</td>
      <td>0</td>
      <td>0</td>
      <td>81</td>
      <td>0.0</td>
      <td>581.0</td>
      <td>71</td>
      <td>202</td>
      <td>0.351485</td>
      <td>...</td>
      <td>0.593220</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>103.0</td>
      <td>68</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>105</td>
      <td>247</td>
    </tr>
    <tr>
      <th>77</th>
      <td>77</td>
      <td>76036</td>
      <td>0</td>
      <td>0</td>
      <td>95</td>
      <td>0.0</td>
      <td>1067.0</td>
      <td>135</td>
      <td>286</td>
      <td>0.472027</td>
      <td>...</td>
      <td>0.846153</td>
      <td>23.0</td>
      <td>68.0</td>
      <td>91.0</td>
      <td>166</td>
      <td>36.0</td>
      <td>3.0</td>
      <td>NaN</td>
      <td>102</td>
      <td>347</td>
    </tr>
    <tr>
      <th>83</th>
      <td>83</td>
      <td>76040</td>
      <td>0</td>
      <td>0</td>
      <td>49</td>
      <td>0.0</td>
      <td>290.0</td>
      <td>51</td>
      <td>104</td>
      <td>0.490384</td>
      <td>...</td>
      <td>0.694444</td>
      <td>13.0</td>
      <td>12.0</td>
      <td>25.0</td>
      <td>16</td>
      <td>9.0</td>
      <td>5.0</td>
      <td>NaN</td>
      <td>51</td>
      <td>127</td>
    </tr>
    <tr>
      <th>86</th>
      <td>86</td>
      <td>76041</td>
      <td>0</td>
      <td>0</td>
      <td>21</td>
      <td>0.0</td>
      <td>224.0</td>
      <td>24</td>
      <td>77</td>
      <td>0.311688</td>
      <td>...</td>
      <td>0.535714</td>
      <td>17.0</td>
      <td>28.0</td>
      <td>45.0</td>
      <td>15</td>
      <td>4.0</td>
      <td>5.0</td>
      <td>22.0</td>
      <td>42</td>
      <td>63</td>
    </tr>
    <tr>
      <th>96</th>
      <td>96</td>
      <td>76048</td>
      <td>0</td>
      <td>0</td>
      <td>44</td>
      <td>0.0</td>
      <td>370.0</td>
      <td>65</td>
      <td>166</td>
      <td>0.391566</td>
      <td>...</td>
      <td>0.630434</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>82.0</td>
      <td>9</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>47</td>
      <td>159</td>
    </tr>
    <tr>
      <th>98</th>
      <td>98</td>
      <td>76049</td>
      <td>0</td>
      <td>0</td>
      <td>1</td>
      <td>0.0</td>
      <td>10.0</td>
      <td>0</td>
      <td>4</td>
      <td>0.000000</td>
      <td>...</td>
      <td>0.750000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>2.0</td>
      <td>0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>3</td>
    </tr>
    <tr>
      <th>111</th>
      <td>111</td>
      <td>76053</td>
      <td>0</td>
      <td>0</td>
      <td>7</td>
      <td>0.0</td>
      <td>110.0</td>
      <td>22</td>
      <td>56</td>
      <td>0.392857</td>
      <td>...</td>
      <td>0.461538</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>32.0</td>
      <td>4</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>10</td>
      <td>50</td>
    </tr>
    <tr>
      <th>115</th>
      <td>115</td>
      <td>76055</td>
      <td>0</td>
      <td>0</td>
      <td>218</td>
      <td>0.0</td>
      <td>2666.0</td>
      <td>300</td>
      <td>831</td>
      <td>0.361010</td>
      <td>...</td>
      <td>0.695121</td>
      <td>241.0</td>
      <td>579.0</td>
      <td>820.0</td>
      <td>149</td>
      <td>43.0</td>
      <td>96.0</td>
      <td>14.0</td>
      <td>384</td>
      <td>771</td>
    </tr>
    <tr>
      <th>118</th>
      <td>118</td>
      <td>76056</td>
      <td>0</td>
      <td>0</td>
      <td>713</td>
      <td>0.0</td>
      <td>24897.0</td>
      <td>5628</td>
      <td>13354</td>
      <td>0.421446</td>
      <td>...</td>
      <td>0.809500</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>6129.0</td>
      <td>1665</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>2764</td>
      <td>16266</td>
    </tr>
    <tr>
      <th>121</th>
      <td>121</td>
      <td>76061</td>
      <td>0</td>
      <td>0</td>
      <td>19</td>
      <td>0.0</td>
      <td>110.0</td>
      <td>11</td>
      <td>37</td>
      <td>0.297297</td>
      <td>...</td>
      <td>0.500000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>39.0</td>
      <td>3</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>13</td>
      <td>28</td>
    </tr>
    <tr>
      <th>125</th>
      <td>125</td>
      <td>76060</td>
      <td>0</td>
      <td>0</td>
      <td>153</td>
      <td>0.0</td>
      <td>NaN</td>
      <td>347</td>
      <td>1176</td>
      <td>0.295068</td>
      <td>...</td>
      <td>0.692000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>89.0</td>
      <td>358</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>456</td>
      <td>1040</td>
    </tr>
    <tr>
      <th>126</th>
      <td>126</td>
      <td>76059</td>
      <td>0</td>
      <td>0</td>
      <td>92</td>
      <td>0.0</td>
      <td>975.0</td>
      <td>159</td>
      <td>350</td>
      <td>0.454285</td>
      <td>...</td>
      <td>0.800000</td>
      <td>31.0</td>
      <td>57.0</td>
      <td>88.0</td>
      <td>105</td>
      <td>33.0</td>
      <td>0.0</td>
      <td>79.0</td>
      <td>64</td>
      <td>350</td>
    </tr>
    <tr>
      <th>127</th>
      <td>127</td>
      <td>76062</td>
      <td>0</td>
      <td>0</td>
      <td>31</td>
      <td>0.0</td>
      <td>409.0</td>
      <td>52</td>
      <td>164</td>
      <td>0.317073</td>
      <td>...</td>
      <td>0.623188</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>170.0</td>
      <td>18</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>60</td>
      <td>147</td>
    </tr>
    <tr>
      <th>128</th>
      <td>128</td>
      <td>76063</td>
      <td>0</td>
      <td>0</td>
      <td>114</td>
      <td>0.0</td>
      <td>1177.0</td>
      <td>163</td>
      <td>447</td>
      <td>0.364653</td>
      <td>...</td>
      <td>0.759689</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>116.0</td>
      <td>139</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>233</td>
      <td>424</td>
    </tr>
    <tr>
      <th>129</th>
      <td>129</td>
      <td>76064</td>
      <td>0</td>
      <td>0</td>
      <td>55</td>
      <td>0.0</td>
      <td>594.0</td>
      <td>128</td>
      <td>277</td>
      <td>0.462093</td>
      <td>...</td>
      <td>0.865384</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>152.0</td>
      <td>24</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>54</td>
      <td>301</td>
    </tr>
    <tr>
      <th>132</th>
      <td>132</td>
      <td>76065</td>
      <td>0</td>
      <td>0</td>
      <td>11</td>
      <td>0.0</td>
      <td>86.0</td>
      <td>12</td>
      <td>35</td>
      <td>0.342857</td>
      <td>...</td>
      <td>0.733333</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>14.0</td>
      <td>17</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>15</td>
      <td>35</td>
    </tr>
    <tr>
      <th>137</th>
      <td>137</td>
      <td>76068</td>
      <td>0</td>
      <td>0</td>
      <td>7</td>
      <td>0.0</td>
      <td>46.0</td>
      <td>2</td>
      <td>15</td>
      <td>0.133333</td>
      <td>...</td>
      <td>1.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.0</td>
      <td>5</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>12</td>
      <td>5</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>4225</th>
      <td>4225</td>
      <td>78586</td>
      <td>0</td>
      <td>0</td>
      <td>63</td>
      <td>0.0</td>
      <td>1308.0</td>
      <td>79</td>
      <td>264</td>
      <td>0.299242</td>
      <td>...</td>
      <td>0.577777</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>210.0</td>
      <td>108</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>172</td>
      <td>236</td>
    </tr>
    <tr>
      <th>4226</th>
      <td>4226</td>
      <td>78585</td>
      <td>0</td>
      <td>0</td>
      <td>143</td>
      <td>0.0</td>
      <td>1498.0</td>
      <td>345</td>
      <td>809</td>
      <td>0.426452</td>
      <td>...</td>
      <td>0.772727</td>
      <td>59.0</td>
      <td>108.0</td>
      <td>167.0</td>
      <td>110</td>
      <td>52.0</td>
      <td>4.0</td>
      <td>6.0</td>
      <td>185</td>
      <td>792</td>
    </tr>
    <tr>
      <th>4228</th>
      <td>4228</td>
      <td>78579</td>
      <td>0</td>
      <td>0</td>
      <td>410</td>
      <td>0.0</td>
      <td>5768.0</td>
      <td>841</td>
      <td>2261</td>
      <td>0.371959</td>
      <td>...</td>
      <td>0.676806</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>2144.0</td>
      <td>307</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>901</td>
      <td>2216</td>
    </tr>
    <tr>
      <th>4229</th>
      <td>4229</td>
      <td>78580</td>
      <td>0</td>
      <td>0</td>
      <td>48</td>
      <td>0.0</td>
      <td>322.0</td>
      <td>63</td>
      <td>177</td>
      <td>0.355932</td>
      <td>...</td>
      <td>0.732142</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>47.0</td>
      <td>41</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>32</td>
      <td>167</td>
    </tr>
    <tr>
      <th>4234</th>
      <td>4234</td>
      <td>78583</td>
      <td>0</td>
      <td>0</td>
      <td>66</td>
      <td>0.0</td>
      <td>648.0</td>
      <td>83</td>
      <td>211</td>
      <td>0.393364</td>
      <td>...</td>
      <td>0.560000</td>
      <td>22.0</td>
      <td>57.0</td>
      <td>79.0</td>
      <td>83</td>
      <td>34.0</td>
      <td>9.0</td>
      <td>49.0</td>
      <td>69</td>
      <td>194</td>
    </tr>
    <tr>
      <th>4236</th>
      <td>4236</td>
      <td>78587</td>
      <td>0</td>
      <td>0</td>
      <td>16</td>
      <td>0.0</td>
      <td>143.0</td>
      <td>7</td>
      <td>25</td>
      <td>0.280000</td>
      <td>...</td>
      <td>0.500000</td>
      <td>6.0</td>
      <td>10.0</td>
      <td>16.0</td>
      <td>12</td>
      <td>2.0</td>
      <td>0.0</td>
      <td>8.0</td>
      <td>11</td>
      <td>17</td>
    </tr>
    <tr>
      <th>4240</th>
      <td>4240</td>
      <td>78590</td>
      <td>0</td>
      <td>0</td>
      <td>9</td>
      <td>0.0</td>
      <td>193.0</td>
      <td>16</td>
      <td>60</td>
      <td>0.266666</td>
      <td>...</td>
      <td>0.666666</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>47.0</td>
      <td>32</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>20</td>
      <td>36</td>
    </tr>
    <tr>
      <th>4241</th>
      <td>4241</td>
      <td>78591</td>
      <td>0</td>
      <td>0</td>
      <td>11</td>
      <td>0.0</td>
      <td>68.0</td>
      <td>10</td>
      <td>27</td>
      <td>0.370370</td>
      <td>...</td>
      <td>0.875000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>26.0</td>
      <td>2</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>13</td>
      <td>27</td>
    </tr>
    <tr>
      <th>4242</th>
      <td>4242</td>
      <td>78592</td>
      <td>0</td>
      <td>0</td>
      <td>403</td>
      <td>0.0</td>
      <td>7383.0</td>
      <td>1191</td>
      <td>2511</td>
      <td>0.474313</td>
      <td>...</td>
      <td>0.667824</td>
      <td>72.0</td>
      <td>121.0</td>
      <td>828.0</td>
      <td>1003</td>
      <td>68.0</td>
      <td>41.0</td>
      <td>NaN</td>
      <td>682</td>
      <td>2959</td>
    </tr>
    <tr>
      <th>4245</th>
      <td>4245</td>
      <td>78596</td>
      <td>0</td>
      <td>0</td>
      <td>212</td>
      <td>0.0</td>
      <td>2814.0</td>
      <td>396</td>
      <td>863</td>
      <td>0.458864</td>
      <td>...</td>
      <td>0.702127</td>
      <td>281.0</td>
      <td>448.0</td>
      <td>745.0</td>
      <td>128</td>
      <td>74.0</td>
      <td>57.0</td>
      <td>NaN</td>
      <td>368</td>
      <td>1023</td>
    </tr>
    <tr>
      <th>4246</th>
      <td>4246</td>
      <td>78597</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>0.0</td>
      <td>14.0</td>
      <td>3</td>
      <td>10</td>
      <td>0.300000</td>
      <td>...</td>
      <td>1.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>4.0</td>
      <td>2</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>3</td>
      <td>8</td>
    </tr>
    <tr>
      <th>4252</th>
      <td>4252</td>
      <td>78602</td>
      <td>0</td>
      <td>0</td>
      <td>77</td>
      <td>0.0</td>
      <td>1413.0</td>
      <td>237</td>
      <td>516</td>
      <td>0.459302</td>
      <td>...</td>
      <td>0.644144</td>
      <td>78.0</td>
      <td>178.0</td>
      <td>256.0</td>
      <td>142</td>
      <td>60.0</td>
      <td>18.0</td>
      <td>0.0</td>
      <td>182</td>
      <td>617</td>

Same way to deal with the 'MIN' part

In [99]:
miss_MIN = np.where(pd.isnull(data_player_regular_totalstats['MIN']))
miss_MIN

(array([   8,  125,  141,  159,  173,  181,  207,  218,  238,  248,  257,
         259,  288,  298,  313,  336,  338,  376,  378,  411,  445,  446,
         459,  468,  473,  482,  488,  506,  541,  568,  584,  586,  598,
         602,  622,  659,  673,  703,  704,  731,  743,  747,  770,  776,
         799,  811,  825,  828,  840,  853,  865,  868,  915,  920,  960,
         961,  973,  975,  976,  981,  996, 1022, 1030, 1043, 1076, 1077,
        1083, 1085, 1107, 1116, 1125, 1127, 1143, 1144, 1146, 1154, 1159,
        1172, 1181, 1196, 1197, 1224, 1247, 1261, 1267, 1268, 1279, 1290,
        1295, 1298, 1319, 1323, 1338, 1342, 1347, 1355, 1360, 1365, 1368,
        1377, 1386, 1392, 1394, 1412, 1422, 1433, 1479, 1483, 1492, 1494,
        1496, 1505, 1514, 1521, 1526, 1538, 1605, 1616, 1630, 1655, 1663,
        1671, 1674, 1678, 1700, 1706, 1713, 1718, 1735, 1772, 1802, 1804,
        1861, 1877, 1878, 1880, 1883, 1936, 2036, 2038, 2044, 2050, 2052,
        2056, 2058, 2061, 2067, 2070, 2072, 2120, 2121, 2133, 2134, 2135,
        2145, 2151, 2162, 2163, 2169, 2170, 2179, 2183, 2205, 2234, 2236,
        2267, 2268, 2288, 2290, 2306, 2317, 2341, 2350, 2373, 2378, 2382,
        2394, 2401, 2402, 2409, 2414, 2436, 2437, 2459, 2475, 2486, 2490,
        2526, 2564, 2565, 2579, 2587, 2594, 2598, 2611, 2617, 2624, 2627,
        2633, 2640, 2642, 2654, 2658, 2669, 2701, 2709, 2729, 2733, 2734,
        2741, 2746, 2749, 2764, 2775, 2776, 2782, 2801, 2828, 2840, 2844,
        2851, 2852, 2866, 2871, 2872, 2873, 2874, 2884, 2906, 2913, 2920,
        2930, 2953, 2957, 2964, 2972, 2975, 2976, 2979, 2980, 2982, 3010,
        3011, 3016, 3025, 3046, 3120, 3125, 3126, 3130, 3138, 3156, 3176,
        3205, 3209, 3235, 3236, 3246, 3251, 3257, 3296, 3297, 3319, 3321,
        3327, 3328, 3330, 3338, 3353, 3368, 3399, 3404, 3405, 3407, 3408,
        3412, 3420, 3424, 3428, 3447, 3450, 3455, 3457, 3466, 3468, 3473,
        3474, 3482, 3483, 3490, 3495, 3505, 3517, 3556, 3569, 3572, 3618,
        3627, 3635, 3641, 3647, 3648, 3654, 3691, 3711, 3712, 3735, 3742,
        3833, 3834, 3837, 3841, 3849, 3851, 3853, 3857, 3861, 3872, 3924,
        3944, 3957, 3959, 3972, 3974, 4000, 4061, 4067, 4081, 4126, 4133,
        4216, 4262, 4320, 4334], dtype=int64),)

Change the missing part of 'MIN' into 0

In [101]:
data_player_regular_totalstats.ix[miss_MIN[0], 'MIN'] = int(0)
data_player_regular_totalstats.ix[miss_MIN[0],:]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>Unnamed: 0</th>
      <th>PLAYER_ID</th>
      <th>LEAGUE_ID</th>
      <th>TEAM_ID</th>
      <th>GP</th>
      <th>GS</th>
      <th>MIN</th>
      <th>FGM</th>
      <th>FGA</th>
      <th>FG_PCT</th>
      <th>...</th>
      <th>FT_PCT</th>
      <th>OREB</th>
      <th>DREB</th>
      <th>REB</th>
      <th>AST</th>
      <th>STL</th>
      <th>BLK</th>
      <th>TOV</th>
      <th>PF</th>
      <th>PTS</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>8</th>
      <td>8</td>
      <td>76007</td>
      <td>0</td>
      <td>0</td>
      <td>56</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>203</td>
      <td>855</td>
      <td>0.237426</td>
      <td>...</td>
      <td>0.686486</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>37</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>171</td>
      <td>533</td>
    </tr>
    <tr>
      <th>125</th>
      <td>125</td>
      <td>76060</td>
      <td>0</td>
      <td>0</td>
      <td>153</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>347</td>
      <td>1176</td>
      <td>0.295068</td>
      <td>...</td>
      <td>0.692000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>89.0</td>
      <td>358</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>456</td>
      <td>1040</td>
    </tr>
    <tr>
      <th>141</th>
      <td>141</td>
      <td>76071</td>
      <td>0</td>
      <td>0</td>
      <td>30</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>23</td>
      <td>91</td>
      <td>0.252747</td>
      <td>...</td>
      <td>0.542857</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>20</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>46</td>
      <td>65</td>
    </tr>
    <tr>
      <th>159</th>
      <td>159</td>
      <td>76080</td>
      <td>0</td>
      <td>0</td>
      <td>34</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>34</td>
      <td>119</td>
      <td>0.285714</td>
      <td>...</td>
      <td>0.680000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>25</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>24</td>
      <td>119</td>
    </tr>
    <tr>
      <th>173</th>
      <td>173</td>
      <td>76089</td>
      <td>0</td>
      <td>0</td>
      <td>4</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0</td>
      <td>1</td>
      <td>0.000000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>0</td>
    </tr>
    <tr>
      <th>181</th>
      <td>181</td>
      <td>76092</td>
      <td>0</td>
      <td>0</td>
      <td>58</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>53</td>
      <td>263</td>
      <td>0.201520</td>
      <td>...</td>
      <td>0.463768</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>16</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>98</td>
      <td>138</td>
    </tr>
    <tr>
      <th>207</th>
      <td>207</td>
      <td>76111</td>
      <td>0</td>
      <td>0</td>
      <td>58</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>124</td>
      <td>438</td>
      <td>0.283105</td>
      <td>...</td>
      <td>0.594936</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>54</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>164</td>
      <td>295</td>
    </tr>
    <tr>
      <th>218</th>
      <td>218</td>
      <td>76117</td>
      <td>0</td>
      <td>0</td>
      <td>32</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>46</td>
      <td>183</td>
      <td>0.251366</td>
      <td>...</td>
      <td>0.537500</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>84.0</td>
      <td>32</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>83</td>
      <td>135</td>
    </tr>
    <tr>
      <th>238</th>
      <td>238</td>
      <td>76126</td>
      <td>0</td>
      <td>0</td>
      <td>45</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>255</td>
      <td>856</td>
      <td>0.297897</td>
      <td>...</td>
      <td>0.775641</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>54</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>93</td>
      <td>631</td>
    </tr>
    <tr>
      <th>248</th>
      <td>248</td>
      <td>76131</td>
      <td>0</td>
      <td>0</td>
      <td>126</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>749</td>
      <td>2046</td>
      <td>0.366080</td>
      <td>...</td>
      <td>0.769696</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>251.0</td>
      <td>551</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>228</td>
      <td>2006</td>
    </tr>
    <tr>
      <th>257</th>
      <td>257</td>
      <td>76137</td>
      <td>0</td>
      <td>0</td>
      <td>43</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>70</td>
      <td>358</td>
      <td>0.195530</td>
      <td>...</td>
      <td>0.500000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>30</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>98</td>
      <td>162</td>
    </tr>
    <tr>
      <th>259</th>
      <td>259</td>
      <td>76139</td>
      <td>0</td>
      <td>0</td>
      <td>111</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>348</td>
      <td>1313</td>
      <td>0.265041</td>
      <td>...</td>
      <td>0.686781</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>53</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>304</td>
      <td>935</td>
    </tr>
    <tr>
      <th>288</th>
      <td>288</td>
      <td>76155</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>5</td>
      <td>16</td>
      <td>0.312500</td>
      <td>...</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>2</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>6</td>
      <td>10</td>
    </tr>
    <tr>
      <th>298</th>
      <td>298</td>
      <td>76161</td>
      <td>0</td>
      <td>0</td>
      <td>6</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>2</td>
      <td>5</td>
      <td>0.400000</td>
      <td>...</td>
      <td>0.500000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>3</td>
      <td>6</td>
    </tr>
    <tr>
      <th>313</th>
      <td>313</td>
      <td>76171</td>
      <td>0</td>
      <td>0</td>
      <td>56</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>170</td>
      <td>523</td>
      <td>0.325047</td>
      <td>...</td>
      <td>0.651282</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>92</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>137</td>
      <td>467</td>
    </tr>
    <tr>
      <th>336</th>
      <td>336</td>
      <td>76186</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>1</td>
      <td>4</td>
      <td>0.250000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>2.0</td>
      <td>1</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>3</td>
      <td>2</td>
    </tr>
    <tr>
      <th>338</th>
      <td>338</td>
      <td>76188</td>
      <td>0</td>
      <td>0</td>
      <td>93</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>209</td>
      <td>821</td>
      <td>0.254567</td>
      <td>...</td>
      <td>0.712871</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>70</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>169</td>
      <td>634</td>
    </tr>
    <tr>
      <th>376</th>
      <td>376</td>
      <td>76207</td>
      <td>0</td>
      <td>0</td>
      <td>75</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>122</td>
      <td>414</td>
      <td>0.294685</td>
      <td>...</td>
      <td>0.671232</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>53</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>158</td>
      <td>342</td>
    </tr>
    <tr>
      <th>378</th>
      <td>378</td>
      <td>76209</td>
      <td>0</td>
      <td>0</td>
      <td>24</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>26</td>
      <td>74</td>
      <td>0.351351</td>
      <td>...</td>
      <td>0.666666</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>24.0</td>
      <td>4</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>34</td>
      <td>64</td>
    </tr>
    <tr>
      <th>411</th>
      <td>411</td>
      <td>76232</td>
      <td>0</td>
      <td>0</td>
      <td>46</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>36</td>
      <td>134</td>
      <td>0.268656</td>
      <td>...</td>
      <td>0.394736</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>36</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>51</td>
      <td>87</td>
    </tr>
    <tr>
      <th>445</th>
      <td>445</td>
      <td>76254</td>
      <td>0</td>
      <td>0</td>
      <td>58</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>223</td>
      <td>870</td>
      <td>0.256321</td>
      <td>...</td>
      <td>0.626943</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>60</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>115</td>
      <td>567</td>
    </tr>
    <tr>
      <th>446</th>
      <td>446</td>
      <td>76255</td>
      <td>0</td>
      <td>0</td>
      <td>12</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>14</td>
      <td>49</td>
      <td>0.285714</td>
      <td>...</td>
      <td>0.857142</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>1</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>16</td>
      <td>34</td>
    </tr>
    <tr>
      <th>459</th>
      <td>459</td>
      <td>76264</td>
      <td>0</td>
      <td>0</td>
      <td>61</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>187</td>
      <td>661</td>
      <td>0.282904</td>
      <td>...</td>
      <td>0.739130</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>137</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>152</td>
      <td>476</td>
    </tr>
    <tr>
      <th>468</th>
      <td>468</td>
      <td>76284</td>
      <td>0</td>
      <td>0</td>
      <td>82</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>313</td>
      <td>875</td>
      <td>0.357714</td>
      <td>...</td>
      <td>0.688963</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>115</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>336</td>
      <td>832</td>
    </tr>
    <tr>
      <th>473</th>
      <td>473</td>
      <td>76270</td>
      <td>0</td>
      <td>0</td>
      <td>3</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>2</td>
      <td>6</td>
      <td>0.333333</td>
      <td>...</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>3</td>
      <td>4</td>
    </tr>
    <tr>
      <th>482</th>
      <td>482</td>
      <td>76275</td>
      <td>0</td>
      <td>0</td>
      <td>54</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>95</td>
      <td>383</td>
      <td>0.248041</td>
      <td>...</td>
      <td>0.632478</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>39</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>122</td>
      <td>264</td>
    </tr>
    <tr>
      <th>488</th>
      <td>488</td>
      <td>76278</td>
      <td>0</td>
      <td>0</td>
      <td>5</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>0</td>
      <td>3</td>
      <td>0.000000</td>
      <td>...</td>
      <td>0.000000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <th>506</th>
      <td>506</td>
      <td>76287</td>
      <td>0</td>
      <td>0</td>
      <td>35</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>18</td>
      <td>50</td>
      <td>0.360000</td>
      <td>...</td>
      <td>0.482758</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>8</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>20</td>
      <td>50</td>
    </tr>
    <tr>
      <th>541</th>
      <td>541</td>
      <td>76306</td>
      <td>0</td>
      <td>0</td>
      <td>61</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>237</td>
      <td>711</td>
      <td>0.333333</td>
      <td>...</td>
      <td>0.681318</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>179</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>237</td>
      <td>598</td>
    </tr>
    <tr>
      <th>568</th>
      <td>568</td>
      <td>76323</td>
      <td>0</td>
      <td>0</td>
      <td>60</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>87</td>
      <td>356</td>
      <td>0.244382</td>
      <td>...</td>
      <td>0.500000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>31</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>108</td>
      <td>210</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>3711</th>
      <td>3711</td>
      <td>78275</td>
      <td>0</td>
      <td>0</td>
      <td>148</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>315</td>
      <td>1040</td>
      <td>0.302884</td>
      <td>...</td>
      <td>0.692307</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>118</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>227</td>
      <td>783</td>
    </tr>
    <tr>
      <th>3712</th>
      <td>3712</td>
      <td>78276</td>
      <td>0</td>
      <td>0</td>
      <td>166</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>402</td>
      <td>1573</td>
      <td>0.255562</td>
      <td>...</td>
      <td>0.812500</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>188</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>397</td>
      <td>1181</td>
    </tr>
    <tr>
      <th>3735</th>
      <td>3735</td>
      <td>78287</td>
      <td>0</td>
      <td>0</td>
      <td>15</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>5</td>
      <td>26</td>
      <td>0.192307</td>
      <td>...</td>
      <td>0.500000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>0</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>6</td>
      <td>15</td>
    </tr>
    <tr>
      <th>3742</th>
      <td>3742</td>
      <td>78291</td>
      <td>0</td>
      <td>0</td>
      <td>70</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>236</td>
      <td>861</td>
      <td>0.274099</td>
      <td>...</td>
      <td>0.829896</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>162</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>107</td>
      <td>633</td>
    </tr>
    <tr>
      <th>3833</th>
      <td>3833</td>
      <td>78340</td>
      <td>0</td>
      <td>0</td>
      <td>14</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>32</td>
      <td>113</td>
      <td>0.283185</td>
      <td>...</td>
      <td>0.500000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>4</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>42</td>
      <td>78</td>
    </tr>
    <tr>
      <th>3834</th>
      <td>3834</td>
      <td>78341</td>
      <td>0</td>
      <td>0</td>
      <td>61</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>194</td>
      <td>616</td>
      <td>0.314935</td>
      <td>...</td>
      <td>0.800000</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>101</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>191</td>
      <td>552</td>
    </tr>
    <tr>
      <th>3837</th>
      <td>3837</td>
      <td>78344</td>
      <td>0</td>
      <td>0</td>
      <td>39</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>37</td>
      <td>143</td>
      <td>0.258741</td>
      <td>...</td>
      <td>0.515151</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>8</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>47</td>
      <td>91</td>
    </tr>
    <tr>
      <th>3841</th>
      <td>3841</td>
      <td>78346</td>
      <td>0</td>
      <td>0</td>
      <td>131</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>484</td>
      <td>1567</td>
      <td>0.308870</td>
      <td>...</td>
      <td>0.710879</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>455.0</td>
      <td>386</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>427</td>
      <td>1445</td>
    </tr>
    <tr>
      <th>3849</th>
      <td>3849</td>
      <td>78353</td>
      <td>0</td>
      <td>0</td>
      <td>17</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>19</td>
      <td>71</td>
      <td>0.267605</td>
      <td>...</td>
      <td>0.666666</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>10</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>12</td>
      <td>44</td>
    </tr>
    <tr>
      <th>3851</th>
      <td>3851</td>
      <td>78355</td>
      <td>0</td>
      <td>0</td>
      <td>121</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>297</td>
      <td>789</td>
      <td>0.376425</td>
      <td>...</td>
      <td>0.691176</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>113</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>349</td>
      <td>876</td>
    </tr>
    <tr>
      <th>3853</th>
      <td>3853</td>
      <td>78357</td>
      <td>0</td>
      <td>0</td>
      <td>147</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>357</td>
      <td>1451</td>
      <td>0.246037</td>
      <td>...</td>
      <td>0.771117</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>106</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>436</td>
      <td>997</td>
    </tr>
    <tr>
      <th>3857</th>
      <td>3857</td>
      <td>78360</td>
      <td>0</td>
      <td>0</td>
      <td>82</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>226</td>
      <td>814</td>
      <td>0.277641</td>
      <td>...</td>
      <td>0.769662</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>137</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
      <td>141</td>
      <td>589</td>
    </tr>
    <tr>
      <th>3861</th>
      <td>3861</td>
      <td>78363</td>
      <td>0</td>
      <td>0</td>
      <td>128</td>
      <td>0.0</td>
      <td>0.0</td>
      <td>425</td>
      <td>1449</td>

Next, deal with the FG3 part

In [102]:
miss_FG3M = np.where(pd.isnull(data_player_regular_totalstats['FG3M']))
miss_FG3A = np.where(pd.isnull(data_player_regular_totalstats['FG3A']))
miss_FG3_PCT = np.where(pd.isnull(data_player_regular_totalstats['FG3_PCT']))
print(miss_FG3M)
print(miss_FG3A)
print(miss_FG3_PCT)

(array([   1,    7,    8, ..., 4320, 4332, 4334], dtype=int64),)
(array([   1,    7,    8, ..., 4320, 4332, 4334], dtype=int64),)
(array([   1,    2,    6, ..., 4320, 4332, 4334], dtype=int64),)

Find that the missing part of 'FG3M' and 'FG3A' are the same

In [103]:
test_equal = miss_FG3M[0] == miss_FG3A[0]
np.sum(test_equal)/len(test_equal)

1.0

Find that the index of missing part of 'FG3M' is subset of missing part of 'FG3_PCT'

In [104]:
inters_miss_FG3 = set(miss_FG3_PCT[0]) & set(miss_FG3M[0])
inters_miss_FG3 = np.array(list(inters_miss_FG3))
len(inters_miss_FG3) == len(miss_FG3M[0])

True

Change those NaN into 0

In [105]:
data_player_regular_totalstats.ix[miss_FG3A[0], 'FG3A'] = 0
data_player_regular_totalstats.ix[miss_FG3A[0], 'FG3M'] = 0
data_player_regular_totalstats.ix[miss_FG3A[0], 'FG3_PCT'] = 0
data_player_regular_totalstats.ix[miss_FG3A[0], ['FG3A', 'FG3M','FG3_PCT']]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>FG3A</th>
      <th>FG3M</th>
      <th>FG3_PCT</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>7</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>24</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>32</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>37</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>49</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>55</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>60</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>71</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>76</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>77</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>83</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>86</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>96</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>98</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>111</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>115</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>118</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>121</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>125</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>126</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>127</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>128</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>129</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>132</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>137</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>4204</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4216</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4217</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4225</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4226</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4228</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4229</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4240</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4241</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4242</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4245</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4246</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4252</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4254</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4257</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4262</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4273</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4274</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4287</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4298</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4299</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4300</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4301</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4315</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4316</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4318</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4319</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4320</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4332</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4334</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
  </tbody>
</table>
<p>1285 rows Ã— 3 columns</p>
</div>

Deal with the 'FG3_PCT' part that is not contained in the 'FG3M'

In [107]:
comple_miss_FG3 = set(miss_FG3_PCT[0]) - set(miss_FG3A[0])
comple_miss_FG3 = list(comple_miss_FG3); comple_miss_FG3 = np.array(comple_miss_FG3)
comple_miss_FG3 = sorted(comple_miss_FG3)

data_temp1 = data_player_regular_totalstats.ix[comple_miss_FG3, ['FG3M', 'FG3A', 'FG3_PCT']]
data_temp1

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>FG3M</th>
      <th>FG3A</th>
      <th>FG3_PCT</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2</th>
      <td>1.0</td>
      <td>18.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0.0</td>
      <td>2.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>15</th>
      <td>2.0</td>
      <td>15.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>112</th>
      <td>19.0</td>
      <td>85.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>151</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>166</th>
      <td>1.0</td>
      <td>1.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>180</th>
      <td>93.0</td>
      <td>275.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>186</th>
      <td>3.0</td>
      <td>15.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>200</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>217</th>
      <td>73.0</td>
      <td>221.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>224</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>260</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>281</th>
      <td>0.0</td>
      <td>2.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>286</th>
      <td>7.0</td>
      <td>34.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>293</th>
      <td>10.0</td>
      <td>26.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>299</th>
      <td>43.0</td>
      <td>147.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>312</th>
      <td>49.0</td>
      <td>179.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>370</th>
      <td>30.0</td>
      <td>89.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>383</th>
      <td>6.0</td>
      <td>11.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>400</th>
      <td>0.0</td>
      <td>4.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>406</th>
      <td>1.0</td>
      <td>1.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>426</th>
      <td>150.0</td>
      <td>492.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>435</th>
      <td>1.0</td>
      <td>13.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>436</th>
      <td>30.0</td>
      <td>121.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>441</th>
      <td>40.0</td>
      <td>164.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>449</th>
      <td>16.0</td>
      <td>56.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>479</th>
      <td>110.0</td>
      <td>295.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>485</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>499</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>512</th>
      <td>23.0</td>
      <td>115.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>3864</th>
      <td>6.0</td>
      <td>35.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3900</th>
      <td>4.0</td>
      <td>7.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3904</th>
      <td>10.0</td>
      <td>82.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3912</th>
      <td>3.0</td>
      <td>6.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3925</th>
      <td>9.0</td>
      <td>30.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3979</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3986</th>
      <td>10.0</td>
      <td>44.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3994</th>
      <td>3.0</td>
      <td>15.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4010</th>
      <td>0.0</td>
      <td>4.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4011</th>
      <td>1.0</td>
      <td>4.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4038</th>
      <td>0.0</td>
      <td>4.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4039</th>
      <td>1.0</td>
      <td>4.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4053</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4064</th>
      <td>2.0</td>
      <td>6.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4065</th>
      <td>84.0</td>
      <td>251.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4092</th>
      <td>55.0</td>
      <td>200.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4107</th>
      <td>1.0</td>
      <td>6.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4113</th>
      <td>0.0</td>
      <td>1.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4118</th>
      <td>0.0</td>
      <td>2.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4125</th>
      <td>0.0</td>
      <td>2.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4140</th>
      <td>11.0</td>
      <td>66.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4141</th>
      <td>7.0</td>
      <td>52.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4170</th>
      <td>127.0</td>
      <td>384.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4171</th>
      <td>108.0</td>
      <td>454.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4198</th>
      <td>91.0</td>
      <td>384.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4221</th>
      <td>12.0</td>
      <td>41.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4223</th>
      <td>10.0</td>
      <td>40.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4234</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4250</th>
      <td>114.0</td>
      <td>314.0</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4289</th>
      <td>6.0</td>
      <td>23.0</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>246 rows Ã— 3 columns</p>
</div>

There is no missing in 'FG3M' and 'FG3A' in the data_temp1

In [109]:
data_temp1.apply(lambda x: sum(x.isnull()),axis=0)

FG3M         0
FG3A         0
FG3_PCT    246
dtype: int64

So, we can compute the 'FG3_PCT' according to the 'FG3M' and 'FG3A', and if 'FG3A' equals to 0 we change 'FG3_PCT' into 0

In [110]:
data_player_regular_totalstats.ix[comple_miss_FG3, 'FG3_PCT'] = \
    data_player_regular_totalstats.ix[comple_miss_FG3, 'FG3M'] / data_player_regular_totalstats.ix[comple_miss_FG3, 'FG3A']

for i in comple_miss_FG3:
    if data_player_regular_totalstats.ix[i,'FG3A'] == 0:
        data_player_regular_totalstats.ix[i,'FG3_PCT'] = 0

data_player_regular_totalstats.ix[comple_miss_FG3, ['FG3M', 'FG3A', 'FG3_PCT']]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>FG3M</th>
      <th>FG3A</th>
      <th>FG3_PCT</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>2</th>
      <td>1.0</td>
      <td>18.0</td>
      <td>0.055556</td>
    </tr>
    <tr>
      <th>6</th>
      <td>0.0</td>
      <td>2.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>15</th>
      <td>2.0</td>
      <td>15.0</td>
      <td>0.133333</td>
    </tr>
    <tr>
      <th>112</th>
      <td>19.0</td>
      <td>85.0</td>
      <td>0.223529</td>
    </tr>
    <tr>
      <th>151</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>166</th>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.000000</td>
    </tr>
    <tr>
      <th>180</th>
      <td>93.0</td>
      <td>275.0</td>
      <td>0.338182</td>
    </tr>
    <tr>
      <th>186</th>
      <td>3.0</td>
      <td>15.0</td>
      <td>0.200000</td>
    </tr>
    <tr>
      <th>200</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>217</th>
      <td>73.0</td>
      <td>221.0</td>
      <td>0.330317</td>
    </tr>
    <tr>
      <th>224</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>260</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>281</th>
      <td>0.0</td>
      <td>2.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>286</th>
      <td>7.0</td>
      <td>34.0</td>
      <td>0.205882</td>
    </tr>
    <tr>
      <th>293</th>
      <td>10.0</td>
      <td>26.0</td>
      <td>0.384615</td>
    </tr>
    <tr>
      <th>299</th>
      <td>43.0</td>
      <td>147.0</td>
      <td>0.292517</td>
    </tr>
    <tr>
      <th>312</th>
      <td>49.0</td>
      <td>179.0</td>
      <td>0.273743</td>
    </tr>
    <tr>
      <th>370</th>
      <td>30.0</td>
      <td>89.0</td>
      <td>0.337079</td>
    </tr>
    <tr>
      <th>383</th>
      <td>6.0</td>
      <td>11.0</td>
      <td>0.545455</td>
    </tr>
    <tr>
      <th>400</th>
      <td>0.0</td>
      <td>4.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>406</th>
      <td>1.0</td>
      <td>1.0</td>
      <td>1.000000</td>
    </tr>
    <tr>
      <th>426</th>
      <td>150.0</td>
      <td>492.0</td>
      <td>0.304878</td>
    </tr>
    <tr>
      <th>435</th>
      <td>1.0</td>
      <td>13.0</td>
      <td>0.076923</td>
    </tr>
    <tr>
      <th>436</th>
      <td>30.0</td>
      <td>121.0</td>
      <td>0.247934</td>
    </tr>
    <tr>
      <th>441</th>
      <td>40.0</td>
      <td>164.0</td>
      <td>0.243902</td>
    </tr>
    <tr>
      <th>449</th>
      <td>16.0</td>
      <td>56.0</td>
      <td>0.285714</td>
    </tr>
    <tr>
      <th>479</th>
      <td>110.0</td>
      <td>295.0</td>
      <td>0.372881</td>
    </tr>
    <tr>
      <th>485</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>499</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>512</th>
      <td>23.0</td>
      <td>115.0</td>
      <td>0.200000</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>3864</th>
      <td>6.0</td>
      <td>35.0</td>
      <td>0.171429</td>
    </tr>
    <tr>
      <th>3900</th>
      <td>4.0</td>
      <td>7.0</td>
      <td>0.571429</td>
    </tr>
    <tr>
      <th>3904</th>
      <td>10.0</td>
      <td>82.0</td>
      <td>0.121951</td>
    </tr>
    <tr>
      <th>3912</th>
      <td>3.0</td>
      <td>6.0</td>
      <td>0.500000</td>
    </tr>
    <tr>
      <th>3925</th>
      <td>9.0</td>
      <td>30.0</td>
      <td>0.300000</td>
    </tr>
    <tr>
      <th>3979</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>3986</th>
      <td>10.0</td>
      <td>44.0</td>
      <td>0.227273</td>
    </tr>
    <tr>
      <th>3994</th>
      <td>3.0</td>
      <td>15.0</td>
      <td>0.200000</td>
    </tr>
    <tr>
      <th>4010</th>
      <td>0.0</td>
      <td>4.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>4011</th>
      <td>1.0</td>
      <td>4.0</td>
      <td>0.250000</td>
    </tr>
    <tr>
      <th>4038</th>
      <td>0.0</td>
      <td>4.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>4039</th>
      <td>1.0</td>
      <td>4.0</td>
      <td>0.250000</td>
    </tr>
    <tr>
      <th>4053</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>4064</th>
      <td>2.0</td>
      <td>6.0</td>
      <td>0.333333</td>
    </tr>
    <tr>
      <th>4065</th>
      <td>84.0</td>
      <td>251.0</td>
      <td>0.334661</td>
    </tr>
    <tr>
      <th>4092</th>
      <td>55.0</td>
      <td>200.0</td>
      <td>0.275000</td>
    </tr>
    <tr>
      <th>4107</th>
      <td>1.0</td>
      <td>6.0</td>
      <td>0.166667</td>
    </tr>
    <tr>
      <th>4113</th>
      <td>0.0</td>
      <td>1.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>4118</th>
      <td>0.0</td>
      <td>2.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>4125</th>
      <td>0.0</td>
      <td>2.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>4140</th>
      <td>11.0</td>
      <td>66.0</td>
      <td>0.166667</td>
    </tr>
    <tr>
      <th>4141</th>
      <td>7.0</td>
      <td>52.0</td>
      <td>0.134615</td>
    </tr>
    <tr>
      <th>4170</th>
      <td>127.0</td>
      <td>384.0</td>
      <td>0.330729</td>
    </tr>
    <tr>
      <th>4171</th>
      <td>108.0</td>
      <td>454.0</td>
      <td>0.237885</td>
    </tr>
    <tr>
      <th>4198</th>
      <td>91.0</td>
      <td>384.0</td>
      <td>0.236979</td>
    </tr>
    <tr>
      <th>4221</th>
      <td>12.0</td>
      <td>41.0</td>
      <td>0.292683</td>
    </tr>
    <tr>
      <th>4223</th>
      <td>10.0</td>
      <td>40.0</td>
      <td>0.250000</td>
    </tr>
    <tr>
      <th>4234</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.000000</td>
    </tr>
    <tr>
      <th>4250</th>
      <td>114.0</td>
      <td>314.0</td>
      <td>0.363057</td>
    </tr>
    <tr>
      <th>4289</th>
      <td>6.0</td>
      <td>23.0</td>
      <td>0.260870</td>
    </tr>
  </tbody>
</table>
<p>246 rows Ã— 3 columns</p>
</div>

Deal with the 'REB' part

In [112]:
miss_OREB = np.where(pd.isnull(data_player_regular_totalstats['OREB']))
miss_DREB = np.where(pd.isnull(data_player_regular_totalstats['DREB']))
miss_REB = np.where(pd.isnull(data_player_regular_totalstats['REB']))

comple_miss_REB = set(miss_OREB[0]) - set(miss_REB[0])
comple_miss_REB = list(comple_miss_REB); comple_miss_REB = np.array(comple_miss_REB)
comple_miss_REB = sorted(comple_miss_REB)

data_temp2 = data_player_regular_totalstats.ix[comple_miss_REB, ['OREB', 'DREB', 'REB']]
data_temp2

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>OREB</th>
      <th>DREB</th>
      <th>REB</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>7</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>15.0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>47.0</td>
    </tr>
    <tr>
      <th>32</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>177.0</td>
    </tr>
    <tr>
      <th>37</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>329.0</td>
    </tr>
    <tr>
      <th>49</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>56.0</td>
    </tr>
    <tr>
      <th>60</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>45.0</td>
    </tr>
    <tr>
      <th>71</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>69.0</td>
    </tr>
    <tr>
      <th>76</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>103.0</td>
    </tr>
    <tr>
      <th>96</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>82.0</td>
    </tr>
    <tr>
      <th>98</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>2.0</td>
    </tr>
    <tr>
      <th>111</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>32.0</td>
    </tr>
    <tr>
      <th>118</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>6129.0</td>
    </tr>
    <tr>
      <th>121</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>39.0</td>
    </tr>
    <tr>
      <th>125</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>89.0</td>
    </tr>
    <tr>
      <th>127</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>170.0</td>
    </tr>
    <tr>
      <th>128</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>116.0</td>
    </tr>
    <tr>
      <th>129</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>152.0</td>
    </tr>
    <tr>
      <th>132</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>14.0</td>
    </tr>
    <tr>
      <th>137</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>138</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>66.0</td>
    </tr>
    <tr>
      <th>140</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>2463.0</td>
    </tr>
    <tr>
      <th>146</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>7.0</td>
    </tr>
    <tr>
      <th>161</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>1009.0</td>
    </tr>
    <tr>
      <th>187</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>6.0</td>
    </tr>
    <tr>
      <th>192</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>181.0</td>
    </tr>
    <tr>
      <th>196</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>2088.0</td>
    </tr>
    <tr>
      <th>198</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>26.0</td>
    </tr>
    <tr>
      <th>199</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>2939.0</td>
    </tr>
    <tr>
      <th>204</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>1193.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>4099</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>1.0</td>
    </tr>
    <tr>
      <th>4103</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>48.0</td>
    </tr>
    <tr>
      <th>4104</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>77.0</td>
    </tr>
    <tr>
      <th>4127</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>112.0</td>
    </tr>
    <tr>
      <th>4130</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>13.0</td>
    </tr>
    <tr>
      <th>4134</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>2194.0</td>
    </tr>
    <tr>
      <th>4138</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>910.0</td>
    </tr>
    <tr>
      <th>4154</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>240.0</td>
    </tr>
    <tr>
      <th>4155</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>59.0</td>
    </tr>
    <tr>
      <th>4161</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>3.0</td>
    </tr>
    <tr>
      <th>4204</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>116.0</td>
    </tr>
    <tr>
      <th>4217</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>23.0</td>
    </tr>
    <tr>
      <th>4225</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>210.0</td>
    </tr>
    <tr>
      <th>4228</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>2144.0</td>
    </tr>
    <tr>
      <th>4229</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>47.0</td>
    </tr>
    <tr>
      <th>4240</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>47.0</td>
    </tr>
    <tr>
      <th>4241</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>26.0</td>
    </tr>
    <tr>
      <th>4246</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>4.0</td>
    </tr>
    <tr>
      <th>4273</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>230.0</td>
    </tr>
    <tr>
      <th>4274</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>52.0</td>
    </tr>
    <tr>
      <th>4287</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>218.0</td>
    </tr>
    <tr>
      <th>4298</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>4220.0</td>
    </tr>
    <tr>
      <th>4299</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>40.0</td>
    </tr>
    <tr>
      <th>4300</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>94.0</td>
    </tr>
    <tr>
      <th>4301</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>201.0</td>
    </tr>
    <tr>
      <th>4315</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>864.0</td>
    </tr>
    <tr>
      <th>4316</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>732.0</td>
    </tr>
    <tr>
      <th>4318</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>27.0</td>
    </tr>
    <tr>
      <th>4319</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>92.0</td>
    </tr>
    <tr>
      <th>4332</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>46.0</td>
    </tr>
  </tbody>
</table>
<p>689 rows Ã— 3 columns</p>
</div>

In [113]:
data_temp2.apply(lambda x: sum(x.isnull()),axis=0)

OREB    689
DREB    689
REB       0
dtype: int64

We change these NaN in 'OREB' into 0 and 'DREB' in to the number of 'REB'

In [114]:
data_player_regular_totalstats.ix[comple_miss_REB, 'OREB'] = 0
data_player_regular_totalstats.ix[comple_miss_REB, 'DREB'] = data_player_regular_totalstats.ix[comple_miss_REB, 'REB']

As for those that even not contain the data of 'REB', we define those data as 0

In [115]:
inters_miss_REB = set(miss_OREB[0]) & set(miss_REB[0])
inters_miss_REB = list(inters_miss_REB); inters_miss_REB = np.array(inters_miss_REB)
inters_miss_REB = sorted(inters_miss_REB)

data_temp3 = data_player_regular_totalstats.ix[inters_miss_REB, ['OREB', 'DREB', 'REB']]
data_temp3

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>OREB</th>
      <th>DREB</th>
      <th>REB</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>8</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>141</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>159</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>173</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>181</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>207</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>238</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>257</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>259</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>288</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>298</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>313</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>338</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>376</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>411</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>445</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>446</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>459</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>468</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>473</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>482</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>488</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>506</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>541</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>568</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>584</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>586</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>598</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>622</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>659</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>3691</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3711</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3712</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3735</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3742</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3833</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3834</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3837</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3849</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3851</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3853</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3857</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3861</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3872</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3924</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3944</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3957</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3959</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3972</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>3974</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4000</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4061</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4067</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4081</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4126</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4133</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4216</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4262</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4320</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4334</th>
      <td>NaN</td>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>292 rows Ã— 3 columns</p>
</div>

All data in data_temp3 is NaN

In [116]:
data_temp3.apply(lambda x: sum(x.isnull()),axis=0)

OREB    292
DREB    292
REB     292
dtype: int64

In [117]:
data_player_regular_totalstats.ix[inters_miss_REB, 'OREB'] = 0
data_player_regular_totalstats.ix[inters_miss_REB, 'DREB'] = 0
data_player_regular_totalstats.ix[inters_miss_REB, 'REB'] = 0

data_player_regular_totalstats.ix[inters_miss_REB, ['OREB', 'DREB', 'REB']]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>OREB</th>
      <th>DREB</th>
      <th>REB</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>8</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>141</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>159</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>173</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>181</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>207</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>238</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>257</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>259</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>288</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>298</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>313</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>338</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>376</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>411</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>445</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>446</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>459</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>468</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>473</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>482</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>488</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>506</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>541</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>568</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>584</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>586</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>598</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>622</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>659</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>3691</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3711</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3712</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3735</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3742</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3833</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3834</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3837</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3849</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3851</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3853</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3857</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3861</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3872</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3924</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3944</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3957</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3959</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3972</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>3974</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4000</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4061</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4067</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4081</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4126</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4133</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4216</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4262</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4320</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4334</th>
      <td>0.0</td>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
  </tbody>
</table>
<p>292 rows Ã— 3 columns</p>
</div>

As for the steal, block and tornover, we just assign the missing data as 0

In [118]:
miss_STL = np.where(pd.isnull(data_player_regular_totalstats['STL']))
miss_BLK = np.where(pd.isnull(data_player_regular_totalstats['BLK']))
miss_TOV = np.where(pd.isnull(data_player_regular_totalstats['TOV']))

np.sum(miss_STL[0] == miss_BLK[0])

981

the number of miss_STL is the same as the intersection of those 'STL' and 'BLK', so, the data in data_temp4 are all NaN

In [119]:
inters_miss_3 = set(miss_STL[0]) & set(miss_BLK[0])
inters_miss_3 = list(inters_miss_3); inters_miss_3 = np.array(inters_miss_3)
inters_miss_3 = sorted(inters_miss_3)

data_temp4 = data_player_regular_totalstats.ix[inters_miss_3, ['STL','BLK']]
data_temp4

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>STL</th>
      <th>BLK</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>7</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>8</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>11</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>13</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>32</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>37</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>49</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>60</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>71</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>76</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>96</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>98</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>111</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>118</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>121</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>125</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>127</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>128</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>129</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>132</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>137</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>138</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>140</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>141</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>146</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>159</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>161</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>173</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>181</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>187</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>4133</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4134</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4138</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4154</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4155</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4161</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4204</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4216</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4217</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4225</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4228</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4229</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4240</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4241</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4246</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4262</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4273</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4274</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4287</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4298</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4299</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4300</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4301</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4315</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4316</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4318</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4319</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4320</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4332</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4334</th>
      <td>NaN</td>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>981 rows Ã— 2 columns</p>
</div>

As for there are all NaN, so we change them into 0

In [120]:
data_temp4.apply(lambda x: sum(x.isnull()),axis=0)

STL    981
BLK    981
dtype: int64

In [121]:
data_player_regular_totalstats.ix[miss_STL[0], 'STL'] = 0
data_player_regular_totalstats.ix[miss_BLK[0], 'BLK'] = 0
data_player_regular_totalstats.ix[miss_STL[0], ['STL', 'BLK']]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>STL</th>
      <th>BLK</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>7</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>32</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>37</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>49</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>60</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>71</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>76</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>96</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>98</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>111</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>118</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>121</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>125</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>127</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>128</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>129</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>132</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>137</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>138</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>140</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>141</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>146</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>159</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>161</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>173</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>181</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>187</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
      <td>...</td>
    </tr>
    <tr>
      <th>4133</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4134</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4138</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4154</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4155</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4161</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4204</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4216</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4217</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4225</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4228</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4229</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4240</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4241</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4246</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4262</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4273</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4274</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4287</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4298</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4299</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4300</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4301</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4315</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4316</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4318</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4319</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4320</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4332</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4334</th>
      <td>0.0</td>
      <td>0.0</td>
    </tr>
  </tbody>
</table>
<p>981 rows Ã— 2 columns</p>
</div>

In [122]:
data_temp5 = data_player_regular_totalstats.ix[miss_TOV[0], ['TOV']]
data_temp5

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>TOV</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>7</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>8</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>11</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>13</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>16</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>24</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>32</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>37</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>49</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>60</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>71</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>76</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>77</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>83</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>96</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>98</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>111</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>118</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>121</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>125</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>127</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>128</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>129</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>132</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>137</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>138</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>140</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>141</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>146</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>159</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
    </tr>
    <tr>
      <th>4161</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4193</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4203</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4204</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4216</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4217</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4225</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4228</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4229</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4240</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4241</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4242</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4245</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4246</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4254</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4262</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4273</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4274</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4287</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4298</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4299</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4300</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4301</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4315</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4316</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4318</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4319</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4320</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4332</th>
      <td>NaN</td>
    </tr>
    <tr>
      <th>4334</th>
      <td>NaN</td>
    </tr>
  </tbody>
</table>
<p>1183 rows Ã— 1 columns</p>
</div>

Change those NaN into 0

In [123]:
data_player_regular_totalstats.ix[miss_TOV[0], ['TOV']] = 0
data_player_regular_totalstats.ix[miss_TOV[0], ['TOV']]

<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>TOV</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>7</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>8</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>11</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>13</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>16</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>24</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>32</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>37</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>49</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>60</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>71</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>76</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>77</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>83</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>96</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>98</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>111</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>118</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>121</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>125</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>127</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>128</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>129</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>132</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>137</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>138</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>140</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>141</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>146</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>159</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>...</th>
      <td>...</td>
    </tr>
    <tr>
      <th>4161</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4193</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4203</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4204</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4216</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4217</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4225</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4228</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4229</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4240</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4241</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4242</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4245</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4246</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4254</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4262</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4273</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4274</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4287</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4298</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4299</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4300</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4301</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4315</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4316</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4318</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4319</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4320</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4332</th>
      <td>0.0</td>
    </tr>
    <tr>
      <th>4334</th>
      <td>0.0</td>
    </tr>
  </tbody>
</table>
<p>1183 rows Ã— 1 columns</p>
</div>

In [125]:
data_player_regular_totalstats.apply(lambda x: sum(x.isnull()),axis=0)

Unnamed: 0    0
PLAYER_ID     0
LEAGUE_ID     0
TEAM_ID       0
GP            0
GS            0
MIN           0
FGM           0
FGA           0
FG_PCT        0
FG3M          0
FG3A          0
FG3_PCT       0
FTM           0
FTA           0
FT_PCT        0
OREB          0
DREB          0
REB           0
AST           0
STL           0
BLK           0
TOV           0
PF            0
PTS           0
dtype: int64

After checking the data not contain NaN, we save it

In [128]:
data_player_regular_totalstats.to_csv('revised_player_regular_totalstats.csv', index=False)